### PR TITLE
Address issue #504 by adding a space after idno elements inside biblStruct

### PR DESCRIPTION
**Pull request by sydb**
Making this relatively high priority because in quite a few cases the missing space actually makes it very difficult for a user to parse the DOI from the date, for example.

(Note I do not think this requires all 4 invited reviewers; I think as soon as 1 or 2 of said “OK” the assignee can go ahead and merge.)

### CODE REVIEW

**Comment by martindholmes** [comment]
@sydb No takers on this so far. Shall we just go ahead and merge, before things in dev change and it gets more complicated?

**Comment by sydb** [comment]
Hmmm … we (Council) are meeting this weekend. How about I bring it up then to try to move it along?
There. Just added to the agenda. (For North American break-out, Fri 07 @ 19:00Z. Since 3 of the 4 requested reviewers will be there, I think that should be fine.)

**Comment by martindholmes** [comment]
@sydb Sounds good. All this for one leetle waffer-thin space.

**Review by JanelleJenstad — APPROVED** [review]
Looks good. Okay to merge.

**Pull request merged**
