### PR TITLE
improvements for multilingual articles

### PR DESCRIPTION
**Pull request by rvdb**
Note: This is important for editing the upcoming multi-lingual jTEI issue. If possible, it would be much appreciated if this could be merged soon.

### CODE REVIEW

**Comment by ebeshero** [comment]
@rvdb Noted! It looks like this is passing our Stylesheets tests, but it's just failing due to a missing webhook for a Slack dependency. I'm asking @sydb and @hcayless to take a look.

**Review by sydb — APPROVED** [review]
Quite a few of the changes are, I am afraid, over my head. (Or, at least, more than I can handle with time available.) But the few changes I can figure out easily make perfect sense.

I have

1. Run the original test suite (Test/)
2. Run the new test suite (Test2/)
3. Converted my own JTEI paper to PDF with both the usual Stylesheets and this branch.

Both test suites pass, and although there is an extra (empty) `<fo:block>` in the xslfo output with this commit, it looks exactly the same when the PDF is viewed.

Therefore my recommendation is we just pull this without further ado.

**Review by martindholmes — APPROVED** [review]
Looks good to me.

**Comment by ebeshero** [comment]
Thanks @sydb and @martindholmes ! I have just merged the PR, @rvdb .

**Comment by rvdb** [comment]
Many thanks, all, for your quick reviews and merging! And apologies, I was in a hurry and should have taken the time to add a summary at least. Post-hoc, what this PR does:

- Fix for counter-intuitive merging of "main" and "sub" titles (that came to light with articles having a main title in the article's main language and an English subtitle).
- Refinement for generating bi-lingual labels of certain document structures (keywords list, abstract) that can be output in multiple languages. Language of the label is determined by first looking up the language of the concerned document structure, and defaulting to the document's main language.

**Pull request merged**
