### PR TITLE
Cosmetic changes to odd2odd and odd2relax stylesheets

### PR DESCRIPTION
**Pull request by cmsmcq**
This pull requests contains mostly cosmetic changes to the odd2odd.xsl and odd2relax.xsl stylesheets.

1 A few inconsistencies in indentation have been regularized.

2 Some long lines have been broken, so those working in windows of about 80-character width don't need quite so much left-right scrolling.

3 Comments have been added to help readers find their way through the stylesheets.

4 In odd2odd, some references to key odd2odd-CHANGE that used `@ident` as the key have been changed to use `tei:uniqueName(.)` as the key (since that is what the construction of the key uses).  (The location is marked and the change can easily be reverted.)

### CODE REVIEW

**Comment by cmsmcq** [comment]
I see that Github has found it good to inject my changes to the README file into this pull request, although they were made only after the pull request had been created.  Likewise the changes I just made to my local copy of the forked repository to re-synchronize with the TEIC/Stylesheets:dev branch. 

My apologies; those have no business in this pull request; the only changes I am suggesting be pulled are 	a7595e7 and  19936b7.  If I can figure out how to remove the others from the pull request, I will do so.

**Comment by cmsmcq** [comment]
Withdrawing this pull request, in the hopes that doing so will allow me to create a new close request with just the changes intended.

**Comment by cmsmcq** [comment]
GitHub appears to be a write-only kind of repository.  Reopening this pull request, since closing it does not seem to make it possible to create a pull request with only the relevant changes.

**Comment by peterstadler** [comment]
It's probably best to create a new branch (in your fork) and apply the changes you want for the pull request there. Then you create a PR from that branch, merge that branch to your local dev branch and move on from there. (It's most 'gitish' to create a branch for every PR)

**Pull request closed without merging**
