### PR TITLE
misc: fix spelling

### PR DESCRIPTION
**Pull request by jbampton**

### CODE REVIEW

**Comment by martindholmes** [comment]
I see an error in Test (make test) with test31, but Test2 passes OK.

**Comment by martindholmes** [comment]
@jbampton The error in Test is caused by my bugfix in the Stylesheets today: the addition of ul.simple{ list-style-type: none; } to tei.css. If you merge dev into your branch the problem should go away.

**Comment by jbampton** [comment]
Hey @martindholmes I think the branch is up to date:

https://github.com/jbampton/TEIC-Stylesheets/commits/fix-spelling

**Comment by martindholmes** [comment]
@jbampton In that case it's the expected-results that need an update to take account of the change to tei.css, I think.

**Comment by martindholmes** [comment]
@jbampton My mistake -- I had forgotten to commit my changes to Test resulting from my own fix for issue #534. I've done that now; if the Jenkins build for Stylesheets-dev confirms the problem is fixed, then a pull from dev will sort it out.

**Comment by martindholmes** [comment]
@jbampton Stylesheets-dev build is now working, so please pull again.

**Comment by jbampton** [comment]
Thanks @martindholmes all done now

**Review by sydb — APPROVED** [review]
All tests in both Test/ and Test2/ pass on my system.

**Pull request merged**
