### PR TITLE
With @martindholmes do <eg> part of #471

### PR DESCRIPTION
**Pull request by martindholmes**
Update which adds ids and anchors to `<eg>` examples in Guidelines pages, to match what already happens with `<egXML>`s.

### CODE REVIEW

**Comment by martindholmes** [comment]
The build failure looks like it's just due to diffs -- egs have ids and anchors where they didn't before. If the pull request is accepted, the next stage would be to update the tests.

**Comment by sydb** [comment]
I think we should update the tests before the PR is accepted, no?

**Review by JanelleJenstad — APPROVED** [review]
Okay with me!

**Comment by martindholmes** [comment]
@sydb You're right about the tests. Let's do that first.

**Comment by sydb** [comment]
OK, done. There were 4 actual results that were not matching expected results in Test/. I looked at the diff of each, and all differences look appropriate, so I updated the expected_results/.
Note: Boy, am I happy with the new DIFFNOW parameter to Test/Makefile. Made this comparatively easy to do.
All tests (except those with `xelatex`) passing on my local machine, and Mr. Travis seems happy with things now.

**Comment by sydb** [comment]
## Updates

### security CSS change
@martindholmes discovered that using the `@style` attribute for in-line CSS (rather than a `class` attribute to refer to CSS elsewhere) causes problems on some servers due to CORS security restrictions (cross-origin resource sharing). Thus we have changed the `@style` on our new `<a>⚓</a>` to a `@class`. **Warning**: This means that the change here has to be considered along with commit 4bd962e (branch “issue_stylesheet_471_eg_anchors”) in the TEI repo, as that is where the CSS is stored.

### newlines caused ugliness
@npcole, @martindholmes, and I discovered that if an `<eg>` ended in a newline, the “bibliography Show all ⚓” line looks ugly (because it floats too low). We considered various solutions, but decided that

- newlines at the beginning and end of some examples, but not others, makes the example boxes look mildly inconsistent in the _Guidelines_
- better to constrain documents than have “magic” code to strip them in the Stylesheets
- TEI should not restrict the contents of `<eg>` for users, it is just for the _Guidelines_ that newlines should not be at beginning nor end

So we added a constraint (in the “issue_stylesheet_471_eg_anchors” branch of the TEI repo) to the `<eg>` element _in p5odds_ that forbids leading or trailing newline, and updated the _Guidelines_ to match. (If you really want a leading or trailing newline, just put a NO-BREAK SPACE (U+00A0) before the leading newline or after the trailing newline.)

## Upshot

In order to review this PR, you will need to review [TEI repo PR 2079](https://github.com/TEIC/Stylesheets/pull/481#issuecomment-748269928) simultaneously.

**Pull request merged**
