### PR TITLE
fix for handling @w:val[. = "0"] on //w:i and //w:b elements

### PR DESCRIPTION
**Pull request by rvdb**
fixes https://github.com/TEIC/Stylesheets/issues/440

### CODE REVIEW

**Comment by peterstadler** [comment]
@rvdb I just rewrote the history of this branch by going back to your latest commit 215cd4d9fb6cfe7a50864587917980961f4e407b and then rebasing the branch onto current dev. Please do not try to update this branch again (or do any other work within this (=your) branch) since this will probably bring more trouble due to the rewritten history. 

When the tests pass I will merge the PR and we are set :-)

**Comment by rvdb** [comment]
@peterstadler I'll delete it right away. Sorry for the mess, and thanks for cleaning it up. Is this how I should have done it in the first place: rebase instead of pull?

**Comment by peterstadler** [comment]
No, it's hard to tell now what exactly went awry. Anyway, I was just looking back at the issue #440 and found that you were also providing tests which I'd like to add to this PR. Am I right that I only need the second zip file with the basicStyles?

**Comment by rvdb** [comment]
@peterstadler Yep, the second version covers tests for all modified styles in this PR.

**Pull request merged**
