### PR TITLE
Issue 526 mdh pdf links

### PR DESCRIPTION
**Pull request by martindholmes**
Proposed fix for missing links for macros etc. per issue #526.

### CODE REVIEW

**Comment by sydb** [comment]
Nope.
I built the PDF version using this branch (`issue-526-mdh-pdf-links`) of the Stylesheets against the `dev` branch of the Guidelines using Hugh’s Docker container. The PDF still does not have the links you (@martindholmes) specifically mention on the ticket. I believe the problem is that the new line 340 compares against "macro", "datatype", and "model", but not "**class**".

**Comment by sydb** [comment]
Nope.
I went ahead and corrected line 340. (It had "model" where it should have had "class".) But that did not solve the problem. I added debugging code to be sure: the "makeInternalLink" template is being called properly now, but (at least in xviii case) the classes are still not links.
I have removed my debugging code and pushed the fix to line 340 in 8d8ac5f2.
Will spend a few more minutes on this, but then off to bed.

**Comment by martindholmes** [comment]
@sydb are you doing the full pdf build or just the pdfonce?

**Comment by sydb** [comment]
Using `make pdf`, which I think does both `pdfonce` and `pdfrest`.

Found that the `<ident type="class">model.divLike</>` was (reasonably) testing for `id('model.divLike')`, but there **is no** such ID. There is "TEI.model.divLike", which looks like the right thing. So I separated out the test for "class" and prepended “TEI.” to the $dest. Seems to be working, but I am too tired to test carefully.
Updated in a6e34de6.

**Comment by sydb** [comment]
Yes, looks like `make pdf` does `Guidelines.pdf:` (which does `pdfonce`) and `pdf-complete:` (which does `pdfrest`).

**Comment by sydb** [comment]
Note that the headwords (as it were) in “1.4.1 Standard Content Models” on PDF page 16 are still not links. They are encoded as `<ref>`s, not `<ident>`s.
Should we be doing something there, too?

**Comment by martindholmes** [comment]
@sydb did the touch-ups, and we tested with @npcole, so this is ready to merge. A new ticket for the instances of ref rather than ident will be raised.

**Pull request merged**
