### PR TITLE
Add namespace sensitivity to xsl:keys used to process @rendition per …

### PR DESCRIPTION
**Pull request by martindholmes**
Pull request for fix for issue #463.

### CODE REVIEW

**Comment by ebeshero** [comment]
That fix is admirably simple! The way to test this I think will be to make an ODD with some customization in a distinct namespace, and see how the HTML turns out. I'll try it out here...

**Comment by martindholmes** [comment]
@ebeshero Sorry, I should have provided a test file to demonstrate the problem. It just has to be an ODD file with some documentation like this in it:

~~~~~
<egXML xmlns="http://www.tei-c.org/ns/Examples">
  <seg rendition="rnd:upover">g</seg>
</egXML>
~~~~~

The "rnd" prefix will cause an undeclared prefix error, which will go away if the fix is applied.

**Comment by ebeshero** [comment]
@martindholmes I've confirmed your fix works on my testerODD just by running `odd2html.xsl` on dev and then on your branch, so I'm satisfied! But I think @sydb suggests a slightly modified solution in #463.

**Review by ebeshero — APPROVED** [review]
@martindholmes I've confirmed your fix works on my testerODD just by running `odd2html.xsl` on dev and then on your branch, so I'm satisfied! But I think @sydb suggests a slightly modified solution in #463.

**Comment by martindholmes** [comment]
@ebeshero Yes, I think @sydb's version is better, so I'll let him update the pull request (if he wants to) or tell me to update it accordingly.

**Comment by sydb** [comment]
I don’t think I know how to update a pull request. Do I just commit a change to the issue_463_mdh_rendition_ns branch?

**Comment by martindholmes** [comment]
@sydb I think if you commit to that branch, then push, the pull request should be updated automatically.

**Comment by sydb** [comment]
OK, will try, hopefully this afternoon.

**Comment by sydb** [comment]
Pushed 95ffcb2, which implements the fix I mentioned on [the ticket](#463). Let’s see what happens to this PR.

However, my fix uses `ancestor::teix:*`. Is there any reason to look up the ancestor tree? I mean, in the completely bonkers case of
~~~~~xml
<egXML xmlns="http://www.tei-c.org/ns/Examples">
  <p rendition="#duck">Quack, quack!</p>
  <dbk:para rendition="#duck">Waddle, waddle!</dbk:para>
</egXML>
~~~~~
should the `@rendition` on the DocBook paragraph be in the key or not? If yes, or if it doesn’t matter, then we should use parent:: instead of ancestor::, no?

**Comment by martindholmes** [comment]
@sydb ancestor includes parent, no? I think it is important to account for all the instances where @rendition might appear on an element which is not in the tei namespace.

**Comment by martindholmes** [comment]
@sydb 's commit is now part of the pull request.

**Comment by sydb** [comment]
Sorry, @martindholmes, I did not see your 1st comment yesterday, to wit:

> ancestor includes parent, no? I think it is important to account for all the instances where `@rendition` might appear on an element which is not in the TEI namespace.

Yes, the 1 element on the `parent::` axis (we know it is 1, not 0, because the current node is an attribute, namely `@rendition`) is a subset of all (the 4 or more) elements on the `ancestor::` axis.

But I don’t know what “accounting for an instance” means: does it mean include in the EXTRENDITION keys or exclude from them?

Of course, one thing to find out is whether `@rendition="prefixed:value"` throws an error when it is on a DocBook element in a `<teix:egXML>` (or on the `<teix:egXML>` itself).

I hope to test that this morning, but it depends a bit on how much time I end up fighting with CSS for the WWP presentations. :-)

**Comment by martindholmes** [comment]
@sydb The intention is to exclude any `@rendition` attributes which are not on elements in the TEI namespace from the xsl:keys because the process should not attempt to do anything with them at all; by definition it knows nothing about them. To be more specific, I believe the keys should only include `@rendition`s in the empty namespace whose parent element is in the TEI namespace. Those are the `@rendition` attributes on which TEI processing should operate; all others (including any in egXMLs, which were the immediate cause of finding the bug) are not the business of the processor at all.

**Review by sydb — APPROVED** [review]

**Pull request merged**
