### PR TITLE
tidy up FPI generation

### PR DESCRIPTION
**Pull request by sydb**
Address #598:
Only check for FPIs in `<ident>` elements, not `<altIdent>` elements.

### CODE REVIEW

**Comment by sydb** [comment]
Passes both Test/ and Test2/ on my local system.

**Comment by sydb** [comment]
_Still_ passes both Test/ and Test2/ on my local system.

**Review by HelenaSabel — APPROVED** [review]

**Comment by sydb** [comment]
_Still_ passes both Test/ and Test2/ on my local system, and by now @HelenaSabel has approved. I am guessing she just did not notice she was also the assignee, so I am just going to merge.

**Comment by sydb** [comment]
No, this branch cannot quite be deleted yet (nor this ticket closed), because there is still a wee bit more to do. (Not sure why it was not done earlier.) In particular, lines 234 & 1311 of odd2dtd.xsl still have references to `altIdent[ @type eq 'FPI']`.

**Pull request merged**
