### PR TITLE
Fix: creation of empty `attList` in  odd2odd.xsl

### PR DESCRIPTION
**Pull request by bwbohl**
addresses #319

This is a local fix for `elementSpec` and probably these changes should be made in a more general way.

### CODE REVIEW

**Comment by sydb** [comment]
OK. I have now reproduced the basic change you made for elements (putting the output `<attList>` in a conditional) to attribute lists in classes. I have checked that change into your patch-1 branch (hope you don’t mind), and also merged in the latest from our dev branch while I was there. It is passing all tests (from both Test/ and Test2/) that run on my system.

Can either @bwbohl or @lb42 provide a sample ODD that fails due to an `<attList>` that has had all its attrs removed? (Then we can test it against the new code, here.)

(BTW, still  moderately pessimistic about inclusion in next release, for although this is not a complex fix, there are a dozen others also trying to get into next release :-)

**Comment by lb42** [comment]
The teiSimplePrint odd exhibits this and two other problems according to the issue i originally raised some time ago (#319 ... 5 years ago)

**Comment by sydb** [comment]
OK. I tested using Exemplars/tei_simplePrint.odd (Sorry, @lb42, I had misunderstood). I compared the output of the Stylesheets in this branch against the output of the Stylesheets in the issue_2382_eventName branch (the branch I happened to be on at the time), and the only differences are a) the value of the `@source` of `<schemaSpec>` and b) 86 missing empty `<attList>` elements. 

This leads me to believe this is entirely successful, and could be merged.

An incidental finding is that tei_simplePrint.odd is itself invalid. There are duplicate occurrences of 4 different `@xml:id` values ("page1", "rend-it", "LCSH", & "OTASH").

**Review by sydb — APPROVED** [review]

**Review by sydb — APPROVED** [review]
Both of the test failures are the SLACK_WEBHOOK thing, so have nothing to do with the actual XSLT. Thus I think if @joeytakeda (or anyone else) can reproduce a successful of an ODD with a known problem, this can just be merged.

**Comment by lb42** [comment]
Those duplicate xmlid values are however all inside egXML elements where arguably they should be permissible.

**Review by HelenaSabel — APPROVED** [review]

**Comment by HelenaSabel** [comment]
I made a test with and ODD that had the empty `<attList>` issue and it works great. Thank you @bwbohl!
  
I also ran Test and Test2 in my local machine and everything passed. 

I think this is ready to be merged.

**Review by joeytakeda — APPROVED** [review]

**Pull request merged**
